name: sdk-cli-handson-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip
  - notebook
  - ipykernel
  - mlflow
  - pip:
    - azure-ai-ml==1.5.0
    - azureml-mlflow==1.50.0
    - scikit-learn==1.1.1
    - pandas==1.4.3
    - numpy==1.23.1
